# Generated by Django 5.0.4 on 2024-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('tip', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('file', models.JSONField()),
                ('author', models.CharField(max_length=30)),
                ('createTime', models.DateTimeField()),
                ('lastEditTime', models.DateTimeField()),
                ('lastSaveToCloudTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uerID', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('avatar', models.ImageField(upload_to='')),
                ('personalSignature', models.CharField(max_length=100)),
            ],
        ),
    ]
