# Generated by Django 5.0.4 on 2024-05-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotepadServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uerID',
            new_name='userID',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='data/avatar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personalSignature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
